### ISSUE TITLE
build error when compile tfcompile

### ISSUE THREAD

**Issue by yylittlefish** [nuchi/tf-to-xla-to-wasm#1]
Hello,

I'm trying to build the modified tfcompile as your step 1,but I got error:
ERROR: /home/user1/.cache/bazel/_bazel_gtxy00/61b9d301b0bb6b1c1772be342a304d6a/external/llvm/BUILD.bazel:2336:1: C++ compilation of rule '@llvm//:webassembly_disassembler' failed (Exit 1)
external/llvm/lib/Target/WebAssembly/Disassembler/WebAssemblyDisassembler.cpp:37:48: fatal error: WebAssemblyGenDisassemblerTables.inc: No such file or directory
 #include "WebAssemblyGenDisassemblerTables.inc"
                                                ^
compilation terminated.

I checked the bazel-genfiles folder, there indeed not contains WebAssemblyGenDisassemblerTables.inc:
user1@user1-2015:~/Tensorflow/tf-to-xla-to-wasm/tensorflow/bazel-genfiles/external/llvm/lib/Target/WebAssembly$ ls
WebAssemblyGenAsmWriter.inc  WebAssemblyGenFastISel.inc   WebAssemblyGenMCCodeEmitter.inc  WebAssemblyGenSubtargetInfo.inc
WebAssemblyGenDAGISel.inc    WebAssemblyGenInstrInfo.inc  WebAssemblyGenRegisterInfo.inc

I tried to build tfcompile in tensorflow source code which downloaded from tensorflow site, it build successfully.
Do you have any idea why that build error?
my ubuntu is 14.04, 
python 2.7.6, 
bazel 0.18.0

**Comment by nuchi** [comment]
It's been a while since I looked at this, sorry. Did you use the version of tf that I specified, or did you try a later version? It might be that later versions of llvm add extra files or split existing ones. It might also be that I forgot to include some targets.

**Comment by nuchi** [comment]
Maybe try adding that file to https://github.com/nuchi/tf-to-xla-to-wasm/blob/master/wasm-patch.diff#L50 and see if that helps?

**Comment by yylittlefish** [comment]
Hi, nuchi
sorry, maybe I did not describe clearly. I used the code tf-to-xla-to-wasm  you submit, so the tf version is same as yours. I followed this step:
$ git clone --recursive https://github.com/nuchi/tf-to-xla-to-wasm.git
$ cd tf-to-xla-to-wasm/tensorflow
$ git apply ../wasm-patch.diff
$ ./configure # configure with XLA support
$ bazel build --config=opt //tensorflow/compiler/aot:tfcompile
but error occurred..

**Comment by yylittlefish** [comment]
> Maybe try adding that file to https://github.com/nuchi/tf-to-xla-to-wasm/blob/master/wasm-patch.diff#L50 and see if that helps?

that works. thank you!
